package rules;
import bsep.tim4.hospitalApp.model.PatientStatus;
import bsep.tim4.hospitalApp.model.PatientAlarm;
import java.sql.Timestamp;

rule "Patient template rule 0"
	when
		$ps: PatientStatus(patientId == "60ae697db04b8d0648494432", heartRate < 20.0, bodyTemperature < 36.7)
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Timestamp(System.currentTimeMillis()),
		"Custom alarm for patient: " + "60ae697db04b8d0648494432" +
		", heart rate: " + $ps.getHeartRate() +
        " blood pressure: " + $ps.getLowerBloodPressure() + "/" + $ps.getUpperBloodPressure() +
        " respiratory rate: " + $ps.getRespiratoryRate() +
        " temperature: " + $ps.getBodyTemperature()));
        System.out.println("Custom alarm for patient: " + "60ae697db04b8d0648494432" +
        ", heart rate: " + $ps.getHeartRate() +
        " blood pressure: " + $ps.getLowerBloodPressure() + "/" + $ps.getUpperBloodPressure() +
        " respiratory rate: " + $ps.getRespiratoryRate() +
        " temperature: " + $ps.getBodyTemperature());
end


