package rules;

import bsep.tim4.hospitalApp.model.PatientStatus;
import bsep.tim4.hospitalApp.model.PatientAlarm;
import java.sql.Timestamp;

rule "High-blood pressure alarm"
	when
		$ps: PatientStatus(lowerBloodPressure > 90, upperBloodPressure > 130)
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Timestamp(System.currentTimeMillis()),
		"High blood pressure alarm"));
		System.out.println("High blood pressure alarm");
end

rule "High heart rate alarm"
	when
		$ps: PatientStatus(heartRate > 120)
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Timestamp(System.currentTimeMillis()),
		"High heart rate alarm"));
		System.out.println("High heart rate alarm");
end

rule "High body temperature alarm"
	when
		$ps: PatientStatus(bodyTemperature > 37.2)
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Timestamp(System.currentTimeMillis()),
		"High body temperature alarm"));
		System.out.println("High body temperature alarm");
end

rule "High respiratory rate alarm"
	when
		$ps: PatientStatus(respiratoryRate > 20.0)
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Timestamp(System.currentTimeMillis()),
		"High respiratory rate alarm"));
		System.out.println("High respiratory rate alarm");
end