package rules;

import bsep.tim4.hospitalApp.model.PatientStatus;
import bsep.tim4.hospitalApp.model.PatientAlarm;
import java.util.Date;

rule "High blood pressure alarm"
    salience 1
	when
		$ps: PatientStatus(lowerBloodPressure > 80, upperBloodPressure > 130, $patientStatusId: id)
		not (PatientAlarm(patientStatusId == $patientStatusId))
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Date(),
		"High blood pressure alarm: " + $ps.getLowerBloodPressure() + "/" + $ps.getUpperBloodPressure()));
		System.out.println("High blood pressure alarm: " +  + $ps.getLowerBloodPressure() + "/" + $ps.getUpperBloodPressure());
end

rule "Low blood pressure alarm"
    salience 1
	when
		$ps: PatientStatus(lowerBloodPressure < 60, upperBloodPressure < 100, $patientStatusId: id)
		not (PatientAlarm(patientStatusId == $patientStatusId))
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Date(),
		"Low blood pressure alarm: " + $ps.getLowerBloodPressure() + "/" + $ps.getUpperBloodPressure()));
		System.out.println("Low blood pressure alarm: " + $ps.getLowerBloodPressure() + "/" + $ps.getUpperBloodPressure());
end

rule "High heart rate alarm"
    salience 1
	when
		$ps: PatientStatus(heartRate > 80, $patientStatusId: id)
        not (PatientAlarm(patientStatusId == $patientStatusId))
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Date(),
		"High heart rate alarm: " + $ps.getHeartRate()));
		System.out.println("High heart rate alarm: " + $ps.getHeartRate());
end

rule "Low heart rate alarm"
    salience 1
	when
		$ps: PatientStatus(heartRate < 60, $patientStatusId: id)
        not (PatientAlarm(patientStatusId == $patientStatusId))
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Date(),
		"Low heart rate alarm: " + $ps.getHeartRate()));
		System.out.println("Low heart rate alarm: " + $ps.getHeartRate());
end

rule "High body temperature alarm"
    salience 1
	when
		$ps: PatientStatus (bodyTemperature > 37.0, $patientStatusId: id)
        not (PatientAlarm(patientStatusId == $patientStatusId))
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Date(),
		"High body temperature alarm: " + $ps.getBodyTemperature()));
		System.out.println("High body temperature alarm: " + $ps.getBodyTemperature());
end

rule "Low body temperature alarm"
    salience 1
	when
		$ps: PatientStatus(bodyTemperature < 36.0, $patientStatusId: id)
        not (PatientAlarm(patientStatusId == $patientStatusId))
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Date(),
		"Low body temperature alarm: " + $ps.getBodyTemperature()));
		System.out.println("Low body temperature alarm: " + $ps.getBodyTemperature());
end

rule "High respiratory rate alarm"
    salience 1
	when
		$ps: PatientStatus(respiratoryRate > 18, $patientStatusId: id)
        not (PatientAlarm(patientStatusId == $patientStatusId))
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Date(),
		"High respiratory rate alarm: " + $ps.getRespiratoryRate()));
		System.out.println("High respiratory rate alarm: " + $ps.getRespiratoryRate());
end

rule "Low respiratory rate alarm"
    salience 1
	when
		$ps: PatientStatus(respiratoryRate < 12, $patientStatusId: id)
        not (PatientAlarm(patientStatusId == $patientStatusId))
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Date(),
		"Low respiratory rate alarm: " + $ps.getRespiratoryRate()));
		System.out.println("Low respiratory rate alarm: " + $ps.getRespiratoryRate());
end

/*Combinations*/
rule "Code blue alarm"
    salience 2
	when
		$ps: PatientStatus(heartRate < 10, respiratoryRate < 5, $patientStatusId: id)
        not (PatientAlarm(patientStatusId == $patientStatusId))
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Date(),
		"Code blue alarm, heart rate: " + $ps.getHeartRate() + " respiratory rate: " + $ps.getRespiratoryRate()));
		System.out.println("Code blue alarm, heart rate: " + $ps.getHeartRate() + " respiratory rate: "
		 + $ps.getRespiratoryRate());
end

rule "Panic attack alarm"
    salience 2
	when
		$ps: PatientStatus(heartRate > 90, respiratoryRate > 20, $patientStatusId: id)
        not (PatientAlarm(patientStatusId == $patientStatusId))
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Date(),
		"Panic attack alarm, heart rate: " + $ps.getHeartRate() + " respiratory rate: " + $ps.getRespiratoryRate()));
		System.out.println("Panic attack alarm, heart rate: " + $ps.getHeartRate() + " respiratory rate: "
		 + $ps.getRespiratoryRate());
end

rule "Cardiac arrest alarm"
    salience 2
	when
		$ps: PatientStatus(heartRate > 140, lowerBloodPressure > 100, upperBloodPressure > 150,
		respiratoryRate < 5, $patientStatusId: id)
        not (PatientAlarm(patientStatusId == $patientStatusId))
	then
		insert(new PatientAlarm($ps.getPatientId(), $ps.getId(), new Date(),
		"Cardiac arrest alarm, heart rate: " + $ps.getHeartRate() + 
		" blood pressure: " + $ps.getLowerBloodPressure() + "/" + $ps.getUpperBloodPressure() +
		" respiratory rate: " + $ps.getRespiratoryRate()));
		System.out.println("Cardiac arrest alarm, heart rate: " + $ps.getHeartRate() + 
		" blood pressure: " + $ps.getLowerBloodPressure() + "/" + $ps.getUpperBloodPressure() +
		" respiratory rate: " + $ps.getRespiratoryRate());
end