package cep;
import bsep.tim4.hospitalApp.model.Log;
import bsep.tim4.hospitalApp.model.LogLevel;
import bsep.tim4.hospitalApp.model.LogAlarm;
import bsep.tim4.hospitalApp.model.LogAlarmType;
import java.util.Date;

rule "Log template rule 0"
    when
        $log1: Log(processed == false, $source : source, level == "LogLevel.INFO", message != "message", source != "source", type != "type", ipAddress != "ipAddress", error != "error", statusCode == "statusCode")
    then
        insert(new LogAlarm(new Date(), $source, LogAlarmType.BRUTE_FORCE, "Hello"));
        System.out.println("**************** Hello ****************************");
        modify($log1){setProcessed(true);};
end


