package cep;

import bsep.tim4.hospitalApp.model.Log;
import bsep.tim4.hospitalApp.model.LogLevel;
import bsep.tim4.hospitalApp.model.LogAlarm;
import bsep.tim4.hospitalApp.model.LogAlarmType;

import java.util.Date;

rule "Error log"
    when
        $log1: Log(level == "ERROR", processed == false, $source : source)
    then
        insert(new LogAlarm(new Date(), $source, LogAlarmType.ERROR_LOG, "Error log"));
        modify($log1){setProcessed(true);};
end