package cep;

import bsep.tim4.hospitalApp.model.Log;
import bsep.tim4.hospitalApp.model.LogLevel;
import bsep.tim4.hospitalApp.model.LogAlarm;
import bsep.tim4.hospitalApp.model.LogAlarmType;

import java.util.Date;

rule "Error log"
    when
        $log1: Log(level == LogLevel.ERROR, processed == false, $source : source)
    then
        System.out.println("**************** ERROR LOG ****************************");
        insert(new LogAlarm(new Date(), $source, "ERROR_LOG", "Error log"));
        modify($log1){setProcessed(true);};
end