package cep;

import bsep.tim4.hospitalApp.model.Log;
import bsep.tim4.hospitalApp.model.LogLevel;
import bsep.tim4.hospitalApp.model.LogAlarm;
import bsep.tim4.hospitalApp.model.LogAlarmType;

import java.util.Date;

rule "More than 5 login attempts in 1 minute from one username"
    when
        $log1: Log(type == "LOGIN_ERROR", $source: source, processed == false)
        accumulate(
            $log2: Log(
                this != $log1,
                type == "LOGIN_ERROR",
                source == $source,
                processed == false,
                this not after [30s] $log1,
                this not before [30s] $log1
            ),
            $logs: collectList($log2)
        )
        eval($logs.size() >= 5)
    then
        System.out.println("**************** LOGIN FAILED RULE ****************************");
        insert(new LogAlarm(new Date(), $source, LogAlarmType.FAILED_LOGIN, "Many login attempts"));
        modify($log1){setProcessed(true);};
        for (Object obj: $logs) {
            Log log = (Log) obj;
            modify(log){setProcessed(true);};
        }
end